### ISSUE TITLE
possible to add toggle for visibility?

### ISSUE THREAD

**Issue by kleerkoat** [zhuochun/tool-bar-md-writer#1]
love the package, thank you!

**Comment by zhuochun** [comment]
Sorry the issue slipped through my mind. Will check how to add this. Thanks

**Comment by zhuochun** [comment]
Fixed in `v0.2.0`

**Comment by grigorii-horos** [comment]
@zhuochun Please, remove this https://github.com/zhuochun/tool-bar-md-writer/blob/master/lib/tool-bar-markdown-writer.coffee#L21-L22

I have troubles in unknown file types, for example dircolors files, tmux.conf and other.

**Comment by zhuochun** [comment]
@horosgrisa it is configurable in package settings.
