### ISSUE TITLE
Add new post cannot be cancelled

### ISSUE THREAD

**Issue by kit4short** [zhuochun/tool-bar-md-writer#3]
When the add new post button is clicked in the tool bar, the pop up window does not seem to have a way to cancel unless atom is restarted

**Comment by zhuochun** [comment]
Press `ESC` should be able to cancel the dialog.

**Comment by welltemperedpaprika** [comment]
Hi, this issue seems to be still occurring. Any fixes?

**Comment by zhuochun** [comment]
Click somewhere empty in the dialog and then press `ESC`.
