### ISSUE TITLE
Adding buttons for Code and Code Block?

### ISSUE THREAD

**Issue by ttasovac** [zhuochun/tool-bar-md-writer#4]
Hi, 

I was wondering if you would consider adding buttons for Code and Code Block? 

If not —  what would be a proper way for me to extend the tool-bar-md-writer without breaking it when it gets an official update?

All best,
Toma

**Comment by zhuochun** [comment]
Added in `v0.3.0`. Hold `shift` and press `Code` will toggle code block.
