### ISSUE TITLE
One counter for the numbered list 

### ISSUE THREAD

**Issue by WagnerGMD** [zhuochun/tool-bar-md-writer#7]
Hello,

when you create one **ordered list** ~(via the button)~, it's always the same number (1)...
There is a solution to enable or create a counter ? Can you add one option to increment it ? From my point of view, it should by default and it will be also easier to read.

Kind regards.

**Comment by zhuochun** [comment]
With markdown-writer, ordered list are auto-incremented when you press Enter.

Alternative, you can run command `Markdown Writer: Correct Order List Numbers`

**Comment by zhuochun** [comment]
In `v0.3.0`, hold `shift` and press `Ordered List` will trigger `Format Ordered List Numbers`

**Comment by WagnerGMD** [comment]
It seem's to work (very good) after the update (it was the v0.2.0) 
Thank you very much @zhuochun.

**Comment by zhuochun** [comment]
Thanks for the feedback
