### ISSUE TITLE
About the code block

### ISSUE THREAD

**Issue by WagnerGMD** [zhuochun/tool-bar-md-writer#9]
Hello,

I'm wonder if there's one trouble with the **Preview Markdown** or the **Code/Code Block** ? Unless it doesn't work like on GitHub ?
Because if I select several lines and click on the button **Code/Code Block**, it doesn't seem to recognize (or detect) them... In fact, the preview show me just one line instead of plenty.

Kind regards.

**Comment by zhuochun** [comment]
To insert *Code Block*, need to press `shift` then click `Code/Code Block`. The default behaviour is to insert an inline code.

**Comment by WagnerGMD** [comment]
Sometimes Atom is little confusing because (for me it's a new software and) it doesn't work very fine (like the usual Windows OS keyboard shortcuts)...
You're right and thank you very much for the tips.
